<?php
    $citys =  $block -> getCity()->LtsItem;
?>
<div style="display: inline-block">
    <p id="select" style="margin: 0px; margin-left: 10px;"><span id="text-ward"></span>, <span id="text-district"></span>, <span id="text-city"></span></p>
</div>

<style>
    #content select
    {
        margin-bottom: 10px;
    }
    #select span
    {
        font-weight: bold;
    }
    #select
    {
        cursor: pointer;
    }
</style>

<div id="content">
    <select name="city" id="city">
        <?php foreach($citys as $city) { ?>
            <?php if($city->ID == 4) { ?>
                <option selected value="<?= $city->ID; ?>"><?= $city->Title; ?></option>
            <?php } else { ?>
                <option value="<?= $city->ID; ?>"><?= $city->Title; ?></option>
            <?php } ?>
        <?php } ?>
    </select>
    <select name="district" id="district">
    </select>
    <select name="ward" id="ward">
    </select>
</div>
